name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ github.actor }}"

            - uses: actions/checkout@v3

            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: "https://registry.npmjs.org"
                  cache: "yarn" # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

            - run: yarn install

            - name: Lint
              run: |
                  yarn exec prettier -c .

            - name: Build website
              run: |
                  yarn build
